version: '2'

services:

  wordpress:
    image: wordpress
    volumes:
      - "./:/var/www/html/wp-content/plugins/copy-post-to-clipboard"
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
